### CIRCUITS

GET http://localhost:3000/circuits?country=estados%20unidos&mindistance=4.56&maxdistance=5.5 HTTP/1.1
api-key: AySZeB1GLp7LmysDTSRqytAmc2C13iYcYju5dKAdFLjzhGsoYxYRMocHaxR6FOvtRm6kxrTyii9oRwOobtfMEYnBFOfBpccXKfMGntt1AgZrYAVQYwMSkza2msCJtEcfb1r4REdGF1tKULtSdIMG8kbnDjWb5pMGka5iVQ3zTyGKLWc9t0CDenVsxAuRfq6OauJQVGmtOsmiRxYhUBQAcc78n5BkocuCqwfcHFiT3U07JH9gnIEuH2SzK9CRMLG4


###

GET http://localhost:3000/circuits HTTP/1.1
api-key: AySZeB1GLp7LmysDTSRqytAmc2C13iYcYju5dKAdFLjzhGsoYxYRMocHaxR6FOvtRm6kxrTyii9oRwOobtfMEYnBFOfBpccXKfMGntt1AgZrYAVQYwMSkza2msCJtEcfb1r4REdGF1tKULtSdIMG8kbnDjWb5pMGka5iVQ3zTyGKLWc9t0CDenVsxAuRfq6OauJQVGmtOsmiRxYhUBQAcc78n5BkocuCqwfcHFiT3U07JH9gnIEuH2SzK9CRMLG4


### 

POST http://localhost:3000/circuits HTTP/1.1
content-type: application/json

{
    "gp_name": "loquesea",
    "circuit_name": "pepito",
    "location": "tattoine",
    "country": "neverland",
    "distance": 8.234
}

###

PATCH  http://localhost:3000/circuits/12 HTTP/1.1
content-type: application/json

{
    "distance": 7.123
}

###

DELETE http://localhost:3000/circuits/12 HTTP/1.1