### FREE PRACTICES

GET http://localhost:3000/free-practice HTTP/1.1

###

GET http://localhost:3000/free-practice/avg-speed/driver/6 HTTP/1.1

###

GET http://localhost:3000/free-practice/fps/driver/12 HTTP/1.1