### QUALIFYINGS

GET http://localhost:3000/qualifying HTTP/1.1

###

GET http://localhost:3000/qualifying/driver/9 HTTP/1.1

###

GET http://localhost:3000/qualifying/circuit/5 HTTP/1.1

###

GET http://localhost:3000/qualifying/team/3 HTTP/1.1