name: Deploy in production
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      NODE_ENV: 'test'
      APP_PORT: ${{ secrets.APP_PORT }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      API_KEY: ${{ secrets.API_KEY }}
      DSN_SENTRY: ${{ secrets.DSN_SENTRY }}
      SENTRY_ENV: ${{ secrets.SENTRY_ENV}}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: npm ci
      - name: Run unit tests
        run: npm run test
      - name: Learning
        run: echo "$DB_PORT"
      - name: Run E2E tests
        run: npm run test:e2e
